# Generated by Django 5.2.6 on 2025-09-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacs',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('published', models.DateTimeField(blank=True, db_column='Published', null=True)),
                ('company', models.CharField(db_column='Company', max_length=50)),
                ('description', models.TextField(db_column='Description')),
                ('title', models.CharField(db_column='Title', max_length=20)),
            ],
            options={
                'db_table': 'Vacs',
            },
        ),
    ]
