# Generated by Django 5.2.6 on 2025-09-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacs',
            name='title',
            field=models.CharField(db_column='Title', max_length=50),
        ),
    ]
